name: ql_pt78
description: Quan ly PT78 - Noi bo
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  pdf: ^3.10.7
  excel: ^4.0.0
  open_filex: ^4.3.4
  path_provider: ^2.1.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
